#pragma once
#ifndef KEYCODES_HPP
#define KEYCODES_HPP

#define FLUKY_KEY_SPACE              32
#define FLUKY_KEY_APOSTROPHE         39  
#define FLUKY_KEY_COMMA              44  
#define FLUKY_KEY_MINUS              45  
#define FLUKY_KEY_PERIOD             46  
#define FLUKY_KEY_SLASH              47 
#define FLUKY_KEY_0                  48
#define FLUKY_KEY_1                  49
#define FLUKY_KEY_2                  50
#define FLUKY_KEY_3                  51
#define FLUKY_KEY_4                  52
#define FLUKY_KEY_5                  53
#define FLUKY_KEY_6                  54
#define FLUKY_KEY_7                  55
#define FLUKY_KEY_8                  56
#define FLUKY_KEY_9                  57
#define FLUKY_KEY_SEMICOLON          59
#define FLUKY_KEY_EQUAL              61
#define FLUKY_KEY_A                  65
#define FLUKY_KEY_B                  66
#define FLUKY_KEY_C                  67
#define FLUKY_KEY_D                  68
#define FLUKY_KEY_E                  69
#define FLUKY_KEY_F                  70
#define FLUKY_KEY_G                  71
#define FLUKY_KEY_H                  72
#define FLUKY_KEY_I                  73
#define FLUKY_KEY_J                  74
#define FLUKY_KEY_K                  75
#define FLUKY_KEY_L                  76
#define FLUKY_KEY_M                  77
#define FLUKY_KEY_N                  78
#define FLUKY_KEY_O                  79
#define FLUKY_KEY_P                  80
#define FLUKY_KEY_Q                  81
#define FLUKY_KEY_R                  82
#define FLUKY_KEY_S                  83
#define FLUKY_KEY_T                  84
#define FLUKY_KEY_U                  85
#define FLUKY_KEY_V                  86
#define FLUKY_KEY_W                  87
#define FLUKY_KEY_X                  88
#define FLUKY_KEY_Y                  89
#define FLUKY_KEY_Z                  90
#define FLUKY_KEY_LEFT_BRACKET       91
#define FLUKY_KEY_BACKSLASH          92
#define FLUKY_KEY_RIGHT_BRACKET      93
#define FLUKY_KEY_GRAVE_ACCENT       96
#define FLUKY_KEY_WORLD_1            161
#define FLUKY_KEY_WORLD_2            162

/* Function keys */
#define FLUKY_KEY_ESCAPE             256
#define FLUKY_KEY_ENTER              257
#define FLUKY_KEY_TAB                258
#define FLUKY_KEY_BACKSPACE          259
#define FLUKY_KEY_INSERT             260
#define FLUKY_KEY_DELETE             261
#define FLUKY_KEY_RIGHT              262
#define FLUKY_KEY_LEFT               263
#define FLUKY_KEY_DOWN               264
#define FLUKY_KEY_UP                 265
#define FLUKY_KEY_PAGE_UP            266
#define FLUKY_KEY_PAGE_DOWN          267
#define FLUKY_KEY_HOME               268
#define FLUKY_KEY_END                269
#define FLUKY_KEY_CAPS_LOCK          280
#define FLUKY_KEY_SCROLL_LOCK        281
#define FLUKY_KEY_NUM_LOCK           282
#define FLUKY_KEY_PRINT_SCREEN       283
#define FLUKY_KEY_PAUSE              284
#define FLUKY_KEY_F1                 290
#define FLUKY_KEY_F2                 291
#define FLUKY_KEY_F3                 292
#define FLUKY_KEY_F4                 293
#define FLUKY_KEY_F5                 294
#define FLUKY_KEY_F6                 295
#define FLUKY_KEY_F7                 296
#define FLUKY_KEY_F8                 297
#define FLUKY_KEY_F9                 298
#define FLUKY_KEY_F10                299
#define FLUKY_KEY_F11                300
#define FLUKY_KEY_F12                301
#define FLUKY_KEY_F13                302
#define FLUKY_KEY_F14                303
#define FLUKY_KEY_F15                304
#define FLUKY_KEY_F16                305
#define FLUKY_KEY_F17                306
#define FLUKY_KEY_F18                307
#define FLUKY_KEY_F19                308
#define FLUKY_KEY_F20                309
#define FLUKY_KEY_F21                310
#define FLUKY_KEY_F22                311
#define FLUKY_KEY_F23                312
#define FLUKY_KEY_F24                313
#define FLUKY_KEY_F25                314
#define FLUKY_KEY_KP_0               320
#define FLUKY_KEY_KP_1               321
#define FLUKY_KEY_KP_2               322
#define FLUKY_KEY_KP_3               323
#define FLUKY_KEY_KP_4               324
#define FLUKY_KEY_KP_5               325
#define FLUKY_KEY_KP_6               326
#define FLUKY_KEY_KP_7               327
#define FLUKY_KEY_KP_8               328
#define FLUKY_KEY_KP_9               329
#define FLUKY_KEY_KP_DECIMAL         330
#define FLUKY_KEY_KP_DIVIDE          331
#define FLUKY_KEY_KP_MULTIPLY        332
#define FLUKY_KEY_KP_SUBTRACT        333
#define FLUKY_KEY_KP_ADD             334
#define FLUKY_KEY_KP_ENTER           335
#define FLUKY_KEY_KP_EQUAL           336
#define FLUKY_KEY_LEFT_SHIFT         340
#define FLUKY_KEY_LEFT_CONTROL       341
#define FLUKY_KEY_LEFT_ALT           342
#define FLUKY_KEY_LEFT_SUPER         343
#define FLUKY_KEY_RIGHT_SHIFT        344
#define FLUKY_KEY_RIGHT_CONTROL      345
#define FLUKY_KEY_RIGHT_ALT          346
#define FLUKY_KEY_RIGHT_SUPER        347
#define FLUKY_KEY_MENU               348

#define FLUKY_MOUSE_BUTTON_1         0
#define FLUKY_MOUSE_BUTTON_2         1
#define FLUKY_MOUSE_BUTTON_3         2
#define FLUKY_MOUSE_BUTTON_4         3
#define FLUKY_MOUSE_BUTTON_5         4
#define FLUKY_MOUSE_BUTTON_6         5
#define FLUKY_MOUSE_BUTTON_7         6
#define FLUKY_MOUSE_BUTTON_8         7
#define FLUKY_MOUSE_BUTTON_LAST      FLUKY_MOUSE_BUTTON_8
#define FLUKY_MOUSE_BUTTON_LEFT      FLUKY_MOUSE_BUTTON_1
#define FLUKY_MOUSE_BUTTON_RIGHT     FLUKY_MOUSE_BUTTON_2
#define FLUKY_MOUSE_BUTTON_MIDDLE    FLUKY_MOUSE_BUTTON_3 

#endif